name: Data Quality Validation

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  data-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Bağımlılıkları yükle
        run: pip install -r requirements.txt

      - name: Validation çalıştır
        run: python dq_pipeline.py
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}